### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by barrycoleman** [ashleydw/lightbox#151]
Why have you chosen the GPL license? It basically makes your library unusable in anything other than GPL projects. Can you dual license GPL and MIT (MIT is the de facto standard for JQuery and Bootstrap projects)? It would make the toolkit so much more usable. No-one in a corporate environment will be able to use your toolkit with it licensed under GPL.

**Comment by ashleydw** [comment]
I chose GPL because I want modifications to be open sourced, I don't want an individual or company modifying the code extensively and not re-releasing the code for free. It also fell inline with Bootstraps original licensing (Apache2).

However, I'm opening for changing to MIT. Submit a PR with it and i'll get it out in the next version.

In the mean time, why not include the lightbox via a CDN, thus technically not including the package - does that work for you?
