### ISSUE TITLE
navigate_left and navigate_right buttons

### ISSUE THREAD

**Issue by Luciuz** [ashleydw/lightbox#172]
Hello there!
How to achieve this goal? I guess we need to apply corresponding methods of EkkoLightbox. But how to get a current one?

**Comment by ashleydw** [comment]
Not sure what you mean. Can you explain more?

**Comment by Luciuz** [comment]
I have EkkoLightbox gallery and wonna add prev and next buttons.

**Comment by ashleydw** [comment]
There already are prev/next buttons. See the doc's examples and the options `left_arrow_class` `right_arrow_class`

**Comment by Luciuz** [comment]
Yes, but it's only for image gallery. In my case i have a "url" gallery (type="url")

**Comment by Luciuz** [comment]
Yep, but div.ekko-lightbox-nav-overlay is hidden for type=url :c

**Comment by ashleydw** [comment]
Yes because you won't be able to interact with the remote content if the navigation buttons are present. If you want the arrows to overlay everything I suggest you fork the repo and remove https://github.com/ashleydw/lightbox/blob/master/ekko-lightbox.coffee#L269

**Comment by Luciuz** [comment]
OK

**Comment by UnaOmnia** [comment]
I also would like the ability to add my own arrows so that I can position them with the overlay and not the images. Basically, I want the next and previous arrows and close button to be in upper right hand corner all the time. 

Hopefully you can reply otherwise I will just have to try to inject it myself. Mostly, I am looking how to trigger the sliding of the modal content, but I will also check the Bootstrap 3 docs.

**Comment by ashleydw** [comment]
@UnaOmnia in the docs `leftArrow`, `rightArrow`

**Comment by UnaOmnia** [comment]
Yes but i needed them to be positioned with the window or .ekko-lightbox but they we getting stuck in the nav overlay div...

**Comment by UnaOmnia** [comment]
I just injected some divs to .ekko-lightbox onContentLoad or Loaded etc.. The whole thing is JS so JS solution should be fine.
