### ISSUE TITLE
I want lightbox vertical centering

### ISSUE THREAD

**Issue by sylove102** [ashleydw/lightbox#269]
Hello.

I want to apply verticing centering when opening the light box in the remote mode.

Currently is using 5.2.0 version. / use min.js, min.css

I'm always using it well ^^

**Comment by ashleydw** [comment]
https://stackoverflow.com/questions/41377501/how-to-vertically-align-bootstrap-v4-modal-dialogs

**Comment by cseelus** [comment]
Yes, Bootstrap 4 has a class `modal-dialog-centered` which just has to be added to the `modal-dialog` to make it vertically centered. 

Any chance you could implement an option like `verticallyCentered` which would add that class to the modal dialog? Otherwise one would have to manually edit `var dialog` in `ekko-lightbox.js`, which is of course messy.
