### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by legacycode** [ashleydw/lightbox#90]
This is an enhancement. It would be great to have this script AMD compatible to use it with RequireJS/CommonJS.

**Comment by ashleydw** [comment]
I have considered this, but I wouldn't change the existing code for backwards compatibility. Maybe I'll include another script; you're most welcome to create a coffeescript file that generates the module :)

**Comment by sagikazarmark** [comment]
I suggest looking at [this](http://blog.npmjs.org/post/112712169830/making-your-jquery-plugin-work-better-with-npm) post and [this](https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js) snippet. I am not quite sure if it would be a BC break to add such functionality. However at this level it wouldn't add too much either, since jQuery is not really AMD capable ATM.

**Comment by ashleydw** [comment]
#166 supports es6 exports, so this is no longer relevant.
