### ISSUE TITLE
Event triggers

### ISSUE THREAD

**Issue by plaidpowered** [ashleydw/lightbox#96]
This is a feature request.

I'm using your lightbox plugin for a gallery that is supposed to have captions. I don't really expect you to add caption support or anything like that, but what _would_ be helpful is some event triggers so I can hook in and modify the lightbox/modal contents when the lightbox is opened or changed.

So, for instance, I could do:
```javascript
$ (lightbox).on("show.bs.lightbox nextSlide.bs.lightbox prevSlide.bs.lightbox",function(e) {
  //do some content related stuff
})
```
It would also be nice if `e.relatedTarget` pointed to the `<a>` that contains the image so I could grab data attributes from it.

**Comment by ashleydw** [comment]
Does `http://ashleydw.github.io/lightbox/#on-navigate` do what you need? The event is fired every time an image is shown. Basically it uses `onShown` and `onNavigate` (view the page source)

**Comment by plaidscreen** [comment]
Almost - I didn't realize the onNavigate event was there, it'll be quite helpful - even better would be if one of the arguments onNavigate passes is the appropriate `<a>` element the current image was grabbed from (if that's even practically possible), but I'll be able to grab it myself using the itemIndex, so that's enough to do what I need.
